In [1]:
dv = @data(["group A", "group B", "group C"])
dv

LoadError: LoadError: UndefVarError: @data not defined
while loading In[1], in expression starting on line 2

In [2]:
readdir()

15-element Array{ByteString,1}:
 ".ipynb_checkpoints"            
 "GTD-Export.csv"                
 "Tutorial.jl"                   
 "Untitled.ipynb"                
 "cofreewy.txt"                  
 "health.csv"                    
 "juliamaterials.ipynb"          
 "learnJlsanders.ipynb"          
 "learning.jl"                   
 "learningJulia.ipynb"           
 "mydata2.csv"                   
 "myplot.png"                    
 "terrorism-analysis-julia.ipynb"
 "testing.jl"                    
 "tryingjulia.ipynb"             

In [3]:
mydata = readdlm("cofreewy.txt")

25x4 Array{Any,2}:
   "Hour"   "CO"     "Traffic"    "Wind"
  1        2.4     50           -0.2    
  2        1.7     26            0.0    
  3        1.4     16            0.0    
  4        1.2     10            0.0    
  5        1.2     12            0.1    
  6        2.0     41           -0.1    
  7        3.4    157           -0.1    
  8        5.8    276           -0.2    
  9        6.8    282            0.2    
 10        6.6    242            1.0    
 11        6.6    200            2.3    
 12        6.3    186            3.8    
 13        5.8    179            4.6    
 14        5.5    178            5.4    
 15        5.9    203            5.9    
 16        6.8    264            5.9    
 17        7.0    289            5.6    
 18        7.4    308            4.9    
 19        6.4    267            3.8    
 20        5.0    190            2.5    
 21        3.8    125            1.4    
 22        3.5    120            0.6    
 23        3.3    116            0.4  

In [14]:
using DataFrames, DataArrays, #PooledDataArrays

mydata1 = DataFrame(readcsv("GTD-Export.csv"))

LoadError: LoadError: syntax: invalid assignment location
while loading In[14], in expression starting on line 3

In [12]:
readdir()

15-element Array{ByteString,1}:
 ".ipynb_checkpoints"            
 "GTD-Export.csv"                
 "Tutorial.jl"                   
 "Untitled.ipynb"                
 "cofreewy.txt"                  
 "health.csv"                    
 "juliamaterials.ipynb"          
 "learnJlsanders.ipynb"          
 "learning.jl"                   
 "learningJulia.ipynb"           
 "mydata2.csv"                   
 "myplot.png"                    
 "terrorism-analysis-julia.ipynb"
 "testing.jl"                    
 "tryingjulia.ipynb"             

In [15]:
?DataFrame

search: 

An AbstractDataFrame that stores a set of named columns

The columns are normally AbstractVectors stored in memory, particularly a Vector, DataVector, or PooledDataVector.

### Constructors

```julia
DataFrame(columns::Vector{Any}, names::Vector{Symbol})
DataFrame(kwargs...)
DataFrame() # an empty DataFrame
DataFrame(t::Type, nrows::Integer, ncols::Integer) # an empty DataFrame of arbitrary size
DataFrame(column_eltypes::Vector, names::Vector, nrows::Integer)
DataFrame(ds::Vector{Associative})
```

### Arguments

  * `columns` : a Vector{Any} with each column as contents
  * `names` : the column names
  * `kwargs` : the key gives the column names, and the value is the   column contents
  * `t` : elemental type of all columns
  * `nrows`, `ncols` : number of rows and columns
  * `column_eltypes` : elemental type of each column
  * `ds` : a vector of Associatives

Each column in `columns` should be the same length.

### Notes

Most of the default constructors convert columns to `DataArrays`.  The base constructor, `DataFrame(columns::Vector{Any}, names::Vector{Symbol})` does not convert to `DataArrays`.

A `DataFrame` is a lightweight object. As long as columns are not manipulated, creation of a DataFrame from existing AbstractVectors is inexpensive. For example, indexing on columns is inexpensive, but indexing by rows is expensive because copies are made of each column.

Because column types can vary, a DataFrame is not type stable. For performance-critical code, do not index into a DataFrame inside of loops.

### Examples

```julia
df = DataFrame()
v = ["x","y","z"][rand(1:3, 10)]
df1 = DataFrame(Any[[1:10], v, rand(10)], [:A, :B, :C])  # columns are Arrays
df2 = DataFrame(A = 1:10, B = v, C = rand(10))           # columns are DataArrays
dump(df1)
dump(df2)
describe(df2)
head(df1)
df1[:A] + df2[:C]
df1[1:4, 1:2]
df1[[:A,:C]]
df1[1:2, [:A,:C]]
df1[:, [:A,:C]]
df1[:, [1,3]]
df1[1:4, :]
df1[1:4, :C]
df1[1:4, :C] = 40. * df1[1:4, :C]
[df1; df2]  # vcat
[df1  df2]  # hcat
size(df1)
```


DataFrame DataFrames DataFrameRow SubDataFrame GroupedDataFrame



In [20]:
mydat = DataFrame(readcsv("GTD-Export.csv"))
# delete the first row
mydat = deleterows!(mydat, 1)
# make x3 and factor variable

mydat2 = pool!(mydat, [:x3, :x4] )

In [21]:
summary(mydat2[:x3])

LoadError: LoadError: MethodError: `getindex` has no method matching getindex(::Void, ::Symbol)
while loading In[21], in expression starting on line 1

In [22]:
describe(mydat2[:x3])

LoadError: LoadError: MethodError: `getindex` has no method matching getindex(::Void, ::Symbol)
while loading In[22], in expression starting on line 1

In [23]:
levels(mydat2[:x3])

LoadError: LoadError: MethodError: `getindex` has no method matching getindex(::Void, ::Symbol)
while loading In[23], in expression starting on line 1

In [24]:
levels(mydat2)

LoadError: LoadError: MethodError: `levels` has no method matching levels(::Void)
while loading In[24], in expression starting on line 1

In [25]:
methods(levels)

# 3 methods for generic function "levels":
levels(da::DataArrays.DataArray{T,N}) at /Users/arindambose/.julia/v0.4/DataArrays/src/dataarray.jl:740
levels{T}(pda::DataArrays.PooledDataArray{T,R<:Integer,N}) at /Users/arindambose/.julia/v0.4/DataArrays/src/pooleddataarray.jl:354
levels(a::AbstractArray{T,N}) at /Users/arindambose/.julia/v0.4/DataArrays/src/dataarray.jl:760

In [26]:
describe(mydat)

x1
Length  75
Type    Any
NAs     0
NA%     0.0%
Unique  75

x2
Length  75
Type    Any
NAs     0
NA%     0.0%
Unique  70

x3
Length  75
Type    Pooled Any
NAs     0
NA%     0.0%
Unique  4

x4
Length  75
Type    Pooled Any
NAs     0
NA%     0.0%
Unique  42

x5
Length  75
Type    Any
NAs     0
NA%     0.0%
Unique  12

x6
Length  75
Type    Any
NAs     0
NA%     0.0%
Unique  3

x7
Length  75
Type    Any
NAs     0
NA%     0.0%
Unique  7

x8
Length  75
Type    Any
NAs     0
NA%     0.0%
Unique  4

x9
Length  75
Type    Any
NAs     0
NA%     0.0%
Unique  5

x10
Length  75
Type    Any
NAs     0
NA%     0.0%
Unique  5

x11
Length  75
Type    Any
NAs     0
NA%     0.0%
Unique  33

x12
Length  75
Type    Any
NAs     0
NA%     0.0%
Unique  27

x13
Length  75
Type    Any
NAs     0
NA%     0.0%
Unique  9

x14
Length  75
Type    Any
NAs     0
NA%     0.0%
Unique  7

x15
Length  75
Type    Any
NAs     0
NA%     0.0%
Unique  5

x16
Length  75
Type    Any
NAs     0
NA%     0.0%
Unique  2

x17
Length  7

In [27]:
Pkg.clone("git://github.com/nalimilan/FreqTables.jl.git")

INFO: Cloning FreqTables from git://github.com/nalimilan/FreqTables.jl.git
INFO: Computing changes...
INFO: No packages to install, update or remove


In [28]:
using FreqTables

INFO: Precompiling module NamedArrays...
    broadcast(Function, NamedArrays.NamedArray...) at /Users/arindambose/.julia/v0.4/NamedArrays/src/keepnames.jl:47
is ambiguous with: 
    broadcast(Function, DataArrays.PooledDataArray...) at /Users/arindambose/.julia/v0.4/DataArrays/src/broadcast.jl:309.
To fix, define 
    broadcast(Function)
before the new definition.
    +(AbstractArray{#T1<:Number, #N<:Any}, NamedArrays.NamedArray{#T2<:Number, #N<:Any, AT<:Any, DT<:Any}) at /Users/arindambose/.julia/v0.4/NamedArrays/src/arithmetic.jl:34
is ambiguous with: 
    +(DataArrays.DataArray, AbstractArray) at /Users/arindambose/.julia/v0.4/DataArrays/src/operators.jl:326.
To fix, define 
    +(DataArrays.DataArray{#T1<:Number, N<:Any}, NamedArrays.NamedArray{#T2<:Number, N<:Any, AT<:Any, DT<:Any})
before the new definition.
    +(AbstractArray{#T1<:Number, #N<:Any}, NamedArrays.NamedArray{#T2<:Number, #N<:Any, AT<:Any, DT<:Any}) at /Users/arindambose/.julia/v0.4/NamedArrays/src/arithmetic.jl:34


In [29]:
x = repeat(["a", "b", "c"], outer = [100]);

In [30]:
x

300-element Array{ASCIIString,1}:
 "a"
 "b"
 "c"
 "a"
 "b"
 "c"
 "a"
 "b"
 "c"
 "a"
 "b"
 "c"
 "a"
 ⋮  
 "a"
 "b"
 "c"
 "a"
 "b"
 "c"
 "a"
 "b"
 "c"
 "a"
 "b"
 "c"

In [31]:
freqtable(x)

3-element NamedArrays.NamedArray{Int64,1,Array{Int64,1},Tuple{Dict{ASCIIString,Int64}}}
a 100
b 100
c 100


In [32]:
y = repeat(["x", "y", "z"], outer = [100]);

In [33]:
freqtable(x,y)

3x3 NamedArrays.NamedArray{Int64,2,Array{Int64,2},Tuple{Dict{ASCIIString,Int64},Dict{ASCIIString,Int64}}}
Dim1 \ Dim2 x   y   z  
a           100 0   0  
b           0   100 0  
c           0   0   100


In [34]:
mydata

76x24 Array{Any,2}:
             "GTD ID"  …  ""                                                                                                            
 201404090005             ""                                                                                                            
 201403140027             ""                                                                                                            
 201401210002             ""                                                                                                            
 201308080011             ""                                                                                                            
 201306300001          …  ""                                                                                                            
 201306180001             ""                                                                                                            
 201305120011        

In [35]:
mydat

75x24 DataFrames.DataFrame
| Row | x1           | x2           | x3           | x4                   |
|-----|--------------|--------------|--------------|----------------------|
| 1   | 201404090005 | "2014-04-09" | "Pakistan"   | "Islamabad"          |
| 2   | 201403140027 | "2014-03-14" | "Pakistan"   | "Saraband"           |
| 3   | 201401210002 | "2014-01-21" | "Pakistan"   | "Mastung district"   |
| 4   | 201308080011 | "2013-08-08" | "Pakistan"   | "Quetta"             |
| 5   | 201306300001 | "2013-06-30" | "Pakistan"   | "Badaber"            |
| 6   | 201306180001 | "2013-06-18" | "Pakistan"   | "Mardan"             |
| 7   | 201305120011 | "2013-05-12" | "Pakistan"   | "Quetta"             |
| 8   | 201305070004 | "2013-05-06" | "Pakistan"   | "Parachinar"         |
| 9   | 201304290001 | "2013-04-29" | "Pakistan"   | "Peshawar"           |
| 10  | 201304260001 | "2013-04-26" | "Pakistan"   | "Karachi"            |
| 11  | 201304160003 | "2013-04-16" | "Pakistan"   | "Peshawar"           |
⋮
| 64  | 200707160003 | "2007-07-16" | "Pakistan"   | "Dera Ismail Khan"   |
| 65  | 200707150002 | "2007-07-15" | "Pakistan"   | "Dera Ismail Khan"   |
| 66  | 200704280002 | "2007-04-28" | "Pakistan"   | "Charsadda"          |
| 67  | 200704060009 | "2007-04-06" | "Pakistan"   | "Parachinar"         |
| 68  | 200703150001 | "2007-03-15" | "India"      | "Rani Bodli"         |
| 69  | 200701050004 | "2007-01-05" | "India"      | "Sadiya"             |
| 70  | 200611050001 | "2006-11-05" | "India"      | "Guwahati"           |
| 71  | 200602280005 | "2006-02-28" | "India"      | "Unknown"            |
| 72  | 200602090002 | "2006-02-09" | "Pakistan"   | "Hangu"              |
| 73  | 200512080003 | "2005-12-08" | "Bangladesh" | "Netrokona district" |
| 74  | 200511290001 | "2005-11-29" | "Bangladesh" | "Gazipur"            |
| 75  | 200511150002 | "2005-11-15" | "India"      | "Tangmarg"           |

| Row | x5                                               | x6 |
|-----|--------------------------------------------------|----|
| 1   | "United Baloch Army (UBA)"                       | -9 |
| 2   | "Tehrik-i-Taliban Pakistan (TTP)"                | -9 |
| 3   | "Lashkar-e-Jhangvi"                              | -9 |
| 4   | "Tehrik-i-Taliban Pakistan (TTP)"                | -9 |
| 5   | "Tehrik-i-Taliban Pakistan (TTP)"                | -9 |
| 6   | "Unknown"                                        | -9 |
| 7   | "Lashkar-e-Jhangvi"                              | -9 |
| 8   | "Tehrik-i-Taliban Pakistan (TTP)"                | -9 |
| 9   | "Unknown"                                        | -9 |
| 10  | "Tehrik-i-Taliban Pakistan (TTP)"                | -9 |
| 11  | "Tehrik-i-Taliban Pakistan (TTP)"                | -9 |
⋮
| 64  | "Unknown"                                        | 0  |
| 65  | "Unknown"                                        | 0  |
| 66  | "Unknown"                                        | 0  |
| 67  | "Unknown"                                        | 0  |
| 68  | "Naxalites"                                      | 0  |
| 69  | "United Liberation Front of Assam (ULFA)"        | 0  |
| 70  | "Unknown"                                        | 0  |
| 71  | "Communist Party of India - Maoist (CPI-Maoist)" | 1  |
| 72  | "Unknown"                                        | 0  |
| 73  | "Jama'atul Mujahideen Bangladesh (JMB)"          | 0  |
| 74  | "Jama'atul Mujahideen Bangladesh (JMB)"          | 1  |
| 75  | "Unknown"                                        | 0  |

| Row | x7                                     | x8 |
|-----|----------------------------------------|----|
| 1   | 21                                     | 46 |
| 2   | ""                                     | "" |
| 3   | "Tehrik-i-Taliban Pakistan (TTP)"      | 0  |
| 4   | ""                                     | "" |
| 5   | ""                                     | "" |
| 6   | ""                                     | "" |
| 7   | "Islamic Movement of Uzbeki

In [39]:
countrycity = freqtable(mydat[:x5], mydat[:x7])

LoadError: LoadError: MethodError: `isless` has no method matching isless(::Int64, ::SubString{ASCIIString})
Closest candidates are:
  isless(::Real, !Matched::AbstractFloat)
  isless(::Real, !Matched::Real)
  isless(::Integer, !Matched::Char)
  ...
while loading In[39], in expression starting on line 1

In [40]:
ccity = freqtable(mydat, :x5, :x7)

LoadError: LoadError: MethodError: `isless` has no method matching isless(::Int64, ::SubString{ASCIIString})
Closest candidates are:
  isless(::Real, !Matched::AbstractFloat)
  isless(::Real, !Matched::Real)
  isless(::Integer, !Matched::Char)
  ...
while loading In[40], in expression starting on line 1

In [41]:
using RDatasets

  likely near /Users/arindambose/.julia/v0.4/RDatasets/src/dataset.jl:1
  likely near /Users/arindambose/.julia/v0.4/RDatasets/src/dataset.jl:1
  likely near /Users/arindambose/.julia/v0.4/RDatasets/src/datasets.jl:1


In [44]:
iris = dataset("datasets", "iris")
iris[:LongSepal] = iris[:SepalLength] .> 5.0
freqtable(iris, :Species, :LongSepal)

3x2 NamedArrays.NamedArray{Int64,2,Array{Int64,2},Tuple{Dict{ASCIIString,Int64},Dict{Bool,Int64}}}
Species \ LongSepal false true 
setosa              28    22   
versicolor          3     47   
virginica           1     49   


In [45]:
typeof(iris[:LongSepal])

DataArrays.DataArray{Bool,1}

In [49]:
typeof(mydat[:x7])

Array{Any,1}

In [47]:
names(mydat)

24-element Array{Symbol,1}:
 :x1 
 :x2 
 :x3 
 :x4 
 :x5 
 :x6 
 :x7 
 :x8 
 :x9 
 :x10
 :x11
 :x12
 :x13
 :x14
 :x15
 :x16
 :x17
 :x18
 :x19
 :x20
 :x21
 :x22
 :x23
 :x24

In [50]:
freqtable(mydat, :x7, :x8)

LoadError: LoadError: MethodError: `isless` has no method matching isless(::Int64, ::SubString{ASCIIString})
Closest candidates are:
  isless(::Real, !Matched::AbstractFloat)
  isless(::Real, !Matched::Real)
  isless(::Integer, !Matched::Char)
  ...
while loading In[50], in expression starting on line 1

In [51]:
zeros(Int, 2,2)

2x2 Array{Int64,2}:
 0  0
 0  0

In [52]:
?NamedArray

search: 

LoadError: LoadError: "NamedArray" is not defined in module Main
while loading In[52], in expression starting on line 119

NamedArrays

Couldn't find NamedArray
Perhaps you meant NamedArrays, SharedArray or DataArray


In [53]:
using NamedArrays

In [54]:
?NamedArray

search: 

`NamedArray(T::Type, dims::Int...)` creates an uninitialized array with default names for the dimensions (`:A`, `:B`, ...) and indices (`"1"`, `"2"`, ...).


NamedArray NamedArrays NamedMatrix



In [55]:
nres= NamedArray(zeros(Int,2,2),Any[[false,true],[false,true]],["cond1","cond2"])

2x2 NamedArrays.NamedArray{Int64,2,Array{Int64,2},Tuple{Dict{Bool,Int64},Dict{Bool,Int64}}}
cond1 \ cond2 false true 
false         0     0    
true          0     0    


In [56]:
?isa

search: 

```
isa(x, type) -> Bool
```

Determine whether `x` is of the given `type`.


isa isascii isalpha isalnum isapprox isabspath isassigned disable_sigint



In [57]:
?@assert

```
@assert cond [text]
```

Throw an `AssertionError` if `cond` is `false`. Preferred syntax for writing assertions. Message `text` is optionally displayed upon assertion failure.


In [58]:
method(@assert)

LoadError: LoadError: too few arguments
while loading In[58], in expression starting on line 1

In [59]:
method()

LoadError: LoadError: UndefVarError: method not defined
while loading In[59], in expression starting on line 1

In [60]:
method("@assert")

LoadError: LoadError: UndefVarError: method not defined
while loading In[60], in expression starting on line 1

In [62]:
@assert isa(mydat[:x3], Any)

In [63]:
typeof(mydat[:x3])

DataArrays.PooledDataArray{Any,UInt8,1}

In [64]:
describe(mydat[:x3])

Length  75
Type    Pooled Any
NAs     0
NA%     0.0%
Unique  4


In [65]:
?summary

search: 

```
summary(x)
```

Return a string giving a brief description of a value. By default returns `string(typeof(x))`. For arrays, returns strings like "2x2 Float64 Array".


summary summarystats



In [66]:
?summarystats

search: 

No documentation found.

`StatsBase.summarystats` is a generic `Function`.

```julia
# 1 method for generic function "summarystats":
summarystats{T<:Real}(a::AbstractArray{T<:Real,N}) at /Users/arindambose/.julia/v0.4/StatsBase/src/scalarstats.jl:350
```


summarystats



In [67]:
summarystats(mydata, :x3)

LoadError: LoadError: MethodError: `summarystats` has no method matching summarystats(::Array{Any,2}, ::Symbol)
while loading In[67], in expression starting on line 1

In [68]:
method(summarystats)

LoadError: LoadError: UndefVarError: method not defined
while loading In[68], in expression starting on line 1

In [69]:
using Stats

In [70]:
summarystats(mydata, :x3)

LoadError: LoadError: MethodError: `summarystats` has no method matching summarystats(::Array{Any,2}, ::Symbol)
while loading In[70], in expression starting on line 1

In [71]:
summarystats(mydata[:x3])

LoadError: LoadError: indexing Array{Any,2} with types Tuple{Symbol} is not supported
while loading In[71], in expression starting on line 1